# Generated by Django 4.0.3 on 2022-04-05 17:35

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('usertype', models.CharField(choices=[('Stu', 'Student'), ('Teacher', 'Teacher')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('address', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=23)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.userdetnew')),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.CharField(max_length=100)),
                ('stu_profilepic', models.ImageField(upload_to='images')),
                ('stu_address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.userdetnew')),
            ],
        ),
    ]
