# Generated by Django 4.0.3 on 2022-03-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_userdetnew_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.CharField(max_length=100)),
                ('stu_profilepic', models.ImageField(upload_to='images')),
                ('stu_adddress', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.userdetnew')),
            ],
        ),
    ]
