# Generated by Django 4.0.3 on 2022-03-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_stu_adddress_stud_stu_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('address', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=23)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.userdetnew')),
            ],
        ),
    ]
